export const Ddetails = [
    {
        id: "2",
        image: "images/D3.jpeg",
        profile: "images/testD.jpg",
        name: "Adegoke Peter",
        description: "Harvested too many! First 10 people to claim get fresh green peppers.",
        quantity: "2 kg",
        datePosted: "August 3, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "1",
        image: "images/D1.jpeg",
        profile: "images/testC.jpg",
        name: "Daniel Mary",
        description: "A basket of ripe, fresh tomatoes, ready for two people to claim.",
        quantity: "5 kg",
        datePosted: "July 30, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "5",
        image: "images/D2.jpg",
        profile: "images/testB.jpg",
        name: "Okoye Adaobi",
        description: "I'm giving away a fresh, healthy, and lively chicken to one receiver.",
        quantity: "10 kg",
        datePosted: "August 1, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "4",
        image: "images/D3.jpeg",
        name: "Organic Apples",
        description: "Crisp, sweet organic apples freshly picked.",
        quantity: "3 kg",
        datePosted: "July 31, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "3",
        image: "images/D5.jpeg",
        name: "Fresh Carrots",
        description: "Crunchy carrots ideal for snacks or cooking.",
        quantity: "4 kg",
        datePosted: "August 2, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "6",
        image: "images/item-5.jpg",
        name: "Potatoes",
        description: "Freshly harvested potatoes, perfect for various dishes.",
        quantity: "8 kg",
        datePosted: "August 2, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "7",
        image: "images/D3.jpeg",
        name: "Green Peppers",
        description: "Fresh green peppers, perfect for adding flavor.",
        quantity: "2 kg",
        datePosted: "August 3, 2024",
        buttonText: "Claim Now",
    },
];


