export const Ddetails = [
    {
        id: "2",
        image: "images/D3.jpeg",
        name: "Green Peppers",
        description: "Fresh green peppers, perfect for adding flavor.",
        quantity: "2 kg",
        datePosted: "August 3, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "1",
        image: "images/D1.jpeg",
        name: "Fresh Tomatoes",
        description: "A basket of ripe, fresh tomatoes perfect for cooking.",
        quantity: "5 kg",
        datePosted: "July 30, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "5",
        image: "images/D2.jpg",
        name: "Brown Rice",
        description: "Healthy and nutritious brown rice available.",
        quantity: "10 kg",
        datePosted: "August 1, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "4",
        image: "images/D3.jpeg",
        name: "Organic Apples",
        description: "Crisp, sweet organic apples freshly picked.",
        quantity: "3 kg",
        datePosted: "July 31, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "3",
        image: "images/D5.jpeg",
        name: "Fresh Carrots",
        description: "Crunchy carrots ideal for snacks or cooking.",
        quantity: "4 kg",
        datePosted: "August 2, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "6",
        image: "images/item-5.jpg",
        name: "Potatoes",
        description: "Freshly harvested potatoes, perfect for various dishes.",
        quantity: "8 kg",
        datePosted: "August 2, 2024",
        buttonText: "Claim Now",
    },
    {
        id: "7",
        image: "images/D3.jpeg",
        name: "Green Peppers",
        description: "Fresh green peppers, perfect for adding flavor.",
        quantity: "2 kg",
        datePosted: "August 3, 2024",
        buttonText: "Claim Now",
    },
];


